//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
[System.Xml.Serialization.XmlRootAttribute("Configuration", Namespace = "http://www.example.org/MRET", IsNullable = false)]
public partial class ConfigurationType
{

    private string assetsPathField;

    private string environmentsPathField;

    private string assetBundlesPathField;

    private string fBXPathField;

    private string projectsPathField;

    private string templatesPathField;

    private string hudPathField;

    private string audioRecordingPathField;

    private string textAnnotationPathField;

    private string animationsPathField;

    private string pointCloudsPathField;

    private string timeSimulationPathField;

    private ConfigurationTypeColliderMode colliderModeField;

    private string versionField;

    /// <remarks/>
    public string AssetsPath
    {
        get
        {
            return this.assetsPathField;
        }
        set
        {
            this.assetsPathField = value;
        }
    }

    /// <remarks/>
    public string EnvironmentsPath
    {
        get
        {
            return this.environmentsPathField;
        }
        set
        {
            this.environmentsPathField = value;
        }
    }

    /// <remarks/>
    public string AssetBundlesPath
    {
        get
        {
            return this.assetBundlesPathField;
        }
        set
        {
            this.assetBundlesPathField = value;
        }
    }

    /// <remarks/>
    public string FBXPath
    {
        get
        {
            return this.fBXPathField;
        }
        set
        {
            this.fBXPathField = value;
        }
    }

    /// <remarks/>
    public string ProjectsPath
    {
        get
        {
            return this.projectsPathField;
        }
        set
        {
            this.projectsPathField = value;
        }
    }

    /// <remarks/>
    public string TemplatesPath
    {
        get
        {
            return this.templatesPathField;
        }
        set
        {
            this.templatesPathField = value;
        }
    }

    /// <remarks/>
    public string HudPath
    {
        get
        {
            return this.hudPathField;
        }
        set
        {
            this.hudPathField = value;
        }
    }

    /// <remarks/>
    public string AudioRecordingPath
    {
        get
        {
            return this.audioRecordingPathField;
        }
        set
        {
            this.audioRecordingPathField = value;
        }
    }

    /// <remarks/>
    public string TextAnnotationPath
    {
        get
        {
            return this.textAnnotationPathField;
        }
        set
        {
            this.textAnnotationPathField = value;
        }
    }

    /// <remarks/>
    public string AnimationsPath
    {
        get
        {
            return this.animationsPathField;
        }
        set
        {
            this.animationsPathField = value;
        }
    }

    /// <remarks/>
    public string PointCloudsPath
    {
        get
        {
            return this.pointCloudsPathField;
        }
        set
        {
            this.pointCloudsPathField = value;
        }
    }

    /// <remarks/>
    public string TimeSimulationPath
    {
        get
        {
            return this.timeSimulationPathField;
        }
        set
        {
            this.timeSimulationPathField = value;
        }
    }

    /// <remarks/>
    public ConfigurationTypeColliderMode ColliderMode
    {
        get
        {
            return this.colliderModeField;
        }
        set
        {
            this.colliderModeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
public enum ConfigurationTypeColliderMode
{

    /// <remarks/>
    None,

    /// <remarks/>
    Box,

    /// <remarks/>
    NonConvex,
}
