//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 

namespace GSFC.ARVR.MRET.Common.Schemas
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    [System.Xml.Serialization.XmlRootAttribute("Project", Namespace = "http://www.example.org/MRET", IsNullable = false)]
    public partial class ProjectType
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnimationPanels", typeof(AnimationPanelsType))]
        [System.Xml.Serialization.XmlElementAttribute("CurrentView", typeof(ViewType))]
        [System.Xml.Serialization.XmlElementAttribute("Description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Drawings", typeof(DrawingsType))]
        [System.Xml.Serialization.XmlElementAttribute("DualAxisRotatableObjects", typeof(DualAxisRotatableObjectType))]
        [System.Xml.Serialization.XmlElementAttribute("Environment", typeof(VirtualEnvironmentType))]
        [System.Xml.Serialization.XmlElementAttribute("GMSECSources", typeof(GMSECSourcesType))]
        [System.Xml.Serialization.XmlElementAttribute("Marker", typeof(MarkerType))]
        [System.Xml.Serialization.XmlElementAttribute("MatlabConnection", typeof(MatlabConnectionType))]
        [System.Xml.Serialization.XmlElementAttribute("Notes", typeof(NotesType))]
        [System.Xml.Serialization.XmlElementAttribute("ObjectGenerators", typeof(ObjectGeneratorsType))]
        [System.Xml.Serialization.XmlElementAttribute("Parts", typeof(PartsType))]
        [System.Xml.Serialization.XmlElementAttribute("PointClouds", typeof(StaticPointCloudsType))]
        [System.Xml.Serialization.XmlElementAttribute("SavedViews", typeof(ViewType))]
        [System.Xml.Serialization.XmlElementAttribute("VideoSources", typeof(VideoSourceType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class AnimationPanelsType
    {

        private AnimationPanelType[] animationPanelsField;

        private int[] indexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnimationPanels")]
        public AnimationPanelType[] AnimationPanels
        {
            get
            {
                return this.animationPanelsField;
            }
            set
            {
                this.animationPanelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public int[] index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class AnimationPanelType
    {

        private Vector3Type positionField;

        private QuaternionType rotationField;

        private AnimationType animationField;

        private bool aROnlyField;

        private bool vROnlyField;

        /// <remarks/>
        public Vector3Type Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        public QuaternionType Rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }

        /// <remarks/>
        public AnimationType Animation
        {
            get
            {
                return this.animationField;
            }
            set
            {
                this.animationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Only")]
        public bool AROnly
        {
            get
            {
                return this.aROnlyField;
            }
            set
            {
                this.aROnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VR-Only")]
        public bool VROnly
        {
            get
            {
                return this.vROnlyField;
            }
            set
            {
                this.vROnlyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ObjectGeneratorsType
    {

        private ObjectGeneratorType[] objectGeneratorsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectGenerator")]
        public ObjectGeneratorType[] ObjectGenerators
        {
            get
            {
                return this.objectGeneratorsField;
            }
            set
            {
                this.objectGeneratorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ObjectGeneratorType
    {
        private string nameField;

        private UnityTransformType transformField;

        private int[] randomSeedField;

        private int numObjectsField;

        private float[] percentOfHighQualityField;

        private ObjectGenerationPrefabsType lowQualityPrefabsField;
        private ObjectGenerationPrefabsType highQualityPrefabsField;

        private float[] collisionDistanceField;
        private float[] collisionDepthField;
        private int[] collisionLayerMaskField;
        private string[] collisionLayerMaskNameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public UnityTransformType Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomSeed")]
        public int[] RandomSeed
        {
            get
            {
                return this.randomSeedField;
            }
            set
            {
                this.randomSeedField = value;
            }
        }

        /// <remarks/>
        public int NumObjects
        {
            get
            {
                return this.numObjectsField;
            }
            set
            {
                this.numObjectsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PercentOfHighQuality")]
        public float[] PercentOfHighQuality
        {
            get
            {
                return this.percentOfHighQualityField;
            }
            set
            {
                this.percentOfHighQualityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LowQualityPrefabs")]
        public ObjectGenerationPrefabsType LowQualityPrefabs
        {
            get
            {
                return this.lowQualityPrefabsField;
            }
            set
            {
                this.lowQualityPrefabsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HighQualityPrefabs")]
        public ObjectGenerationPrefabsType HighQualityPrefabs
        {
            get
            {
                return this.highQualityPrefabsField;
            }
            set
            {
                this.highQualityPrefabsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollisionDistance")]
        public float[] CollisionDistance
        {
            get
            {
                return this.collisionDistanceField;
            }
            set
            {
                this.collisionDistanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollisionDepth")]
        public float[] CollisionDepth
        {
            get
            {
                return this.collisionDepthField;
            }
            set
            {
                this.collisionDepthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollisionLayerMask")]
        public int[] CollisionLayerMask
        {
            get
            {
                return this.collisionLayerMaskField;
            }
            set
            {
                this.collisionLayerMaskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollisionLayerMaskName")]
        public string[] CollisionLayerMaskName
        {
            get
            {
                return this.collisionLayerMaskNameField;
            }
            set
            {
                this.collisionLayerMaskNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ObjectGenerationPrefabsType
    {
        private ObjectGenerationPrefabType[] prefabField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prefab")]
        public ObjectGenerationPrefabType[] Prefab
        {
            get
            {
                return this.prefabField;
            }
            set
            {
                this.prefabField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ObjectGenerationPrefabType
    {
        private AssetType meshAssetField;

        private AssetType materialAssetField;

        private RandomizePositionType randomizePositionField;

        private RandomizeRotationType randomizeRotationField;

        private RandomizeScaleType randomizeScaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeshAsset")]
        public AssetType MeshAsset
        {
            get
            {
                return this.meshAssetField;
            }
            set
            {
                this.meshAssetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialAsset")]
        public AssetType MaterialAsset
        {
            get
            {
                return this.materialAssetField;
            }
            set
            {
                this.materialAssetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizePosition")]
        public RandomizePositionType RandomizePosition
        {
            get
            {
                return this.randomizePositionField;
            }
            set
            {
                this.randomizePositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizeRotation")]
        public RandomizeRotationType RandomizeRotation
        {
            get
            {
                return this.randomizeRotationField;
            }
            set
            {
                this.randomizeRotationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizeScale")]
        public RandomizeScaleType RandomizeScale
        {
            get
            {
                return this.randomizeScaleField;
            }
            set
            {
                this.randomizeScaleField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class RandomizeType
    {
        private int[] randomSeedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomSeed")]
        public int[] RandomSeed
        {
            get
            {
                return this.randomSeedField;
            }
            set
            {
                this.randomSeedField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class RandomizeTransformType : RandomizeType
    {
        private bool[] randomizeXField;
        private bool[] randomizeYField;
        private bool[] randomizeZField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizeX")]
        public bool[] RandomizeX
        {
            get
            {
                return this.randomizeXField;
            }
            set
            {
                this.randomizeXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizeY")]
        public bool[] RandomizeY
        {
            get
            {
                return this.randomizeYField;
            }
            set
            {
                this.randomizeYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RandomizeZ")]
        public bool[] RandomizeZ
        {
            get
            {
                return this.randomizeZField;
            }
            set
            {
                this.randomizeZField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class RandomizePositionType : RandomizeTransformType
    {
        private DistributionFunctionType[] distributionFunctionTypeField;

        private Vector3Type positionMinField;
        private Vector3Type positionMaxField;

        private Vector3Type positionMeanField;
        private NonNegativeFloat3Type positionStandardDeviationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DistributionType")]
        public DistributionFunctionType[] DistributionType
        {
            get
            {
                return this.distributionFunctionTypeField;
            }
            set
            {
                this.distributionFunctionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PositionMin")]
        public Vector3Type PositionMin
        {
            get
            {
                return this.positionMinField;
            }
            set
            {
                this.positionMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PositionMax")]
        public Vector3Type PositionMax
        {
            get
            {
                return this.positionMaxField;
            }
            set
            {
                this.positionMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PositionMean")]
        public Vector3Type PositionMean
        {
            get
            {
                return this.positionMeanField;
            }
            set
            {
                this.positionMeanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PositionStandardDeviation")]
        public NonNegativeFloat3Type PositionStandardDeviation
        {
            get
            {
                return this.positionStandardDeviationField;
            }
            set
            {
                this.positionStandardDeviationField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class RandomizeRotationType: RandomizeTransformType
    {
        private Degree3Type rotationMinField;
        private Degree3Type rotationMaxField;

        private int[] randomSeedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RotationMin")]
        public Degree3Type RotationMin
        {
            get
            {
                return this.rotationMinField;
            }
            set
            {
                this.rotationMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RotationMax")]
        public Degree3Type RotationMax
        {
            get
            {
                return this.rotationMaxField;
            }
            set
            {
                this.rotationMaxField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class RandomizeScaleType : RandomizeTransformType
    {
        private bool[] maintainAxialRatioField;

        private float[] maintainAxialRatioScaleMinField;
        private float[] maintainAxialRatioScaleMaxField;

        private NonNegativeFloat3Type scaleMinField;
        private NonNegativeFloat3Type scaleMaxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaintainAxialRatio")]
        public bool[] MaintainAxialRatio
        {
            get
            {
                return this.maintainAxialRatioField;
            }
            set
            {
                this.maintainAxialRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaintainAxialRatioScaleMin")]
        public float[] MaintainAxialRatioScaleMin
        {
            get
            {
                return this.maintainAxialRatioScaleMinField;
            }
            set
            {
                this.maintainAxialRatioScaleMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaintainAxialRatioScaleMax")]
        public float[] MaintainAxialRatioScaleMax
        {
            get
            {
                return this.maintainAxialRatioScaleMaxField;
            }
            set
            {
                this.maintainAxialRatioScaleMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScaleMin")]
        public NonNegativeFloat3Type ScaleMin
        {
            get
            {
                return this.scaleMinField;
            }
            set
            {
                this.scaleMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScaleMax")]
        public NonNegativeFloat3Type ScaleMax
        {
            get
            {
                return this.scaleMaxField;
            }
            set
            {
                this.scaleMaxField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class StaticPointCloudsType
    {

        private StaticPointCloudType[] staticPointCloudsField;

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StaticPointClouds")]
        public StaticPointCloudType[] StaticPointClouds
        {
            get
            {
                return this.staticPointCloudsField;
            }
            set
            {
                this.staticPointCloudsField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class MarkerType
    {

        private UnityTransformType locationField;

        private MarkerTypeType typeField;

        private string markerFilePathField;

        /// <remarks/>
        public UnityTransformType Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public MarkerTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string MarkerFilePath
        {
            get
            {
                return this.markerFilePathField;
            }
            set
            {
                this.markerFilePathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum MarkerTypeType
    {

        /// <remarks/>
        Fiducial,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class DrawingType
    {

        private string nameField;

        private string renderTypeField;

        private LineDrawingUnitsType desiredUnitsField;

        private Vector3Type[] pointsField;

        private float widthField;

        private string gUIDField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string RenderType
        {
            get
            {
                return this.renderTypeField;
            }
            set
            {
                this.renderTypeField = value;
            }
        }

        /// <remarks/>
        public LineDrawingUnitsType DesiredUnits
        {
            get
            {
                return this.desiredUnitsField;
            }
            set
            {
                this.desiredUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Points")]
        public Vector3Type[] Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }

        /// <remarks/>
        public float Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public enum LineDrawingUnitsType
    {

        /// <remarks/>
        meters,

        /// <remarks/>
        centimeters,

        /// <remarks/>
        millimeters,

        /// <remarks/>
        yards,

        /// <remarks/>
        feet,

        /// <remarks/>
        inches,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class NoteType
    {

        private string parentNameField;

        private UnityTransformType transformField;

        private NoteTypeState stateField;

        private string titleField;

        private string detailsField;

        private NoteDrawingsType drawingsField;

        private string gUIDField;

        private bool aROnlyField;

        private bool vROnlyField;

        /// <remarks/>
        public string ParentName
        {
            get
            {
                return this.parentNameField;
            }
            set
            {
                this.parentNameField = value;
            }
        }

        /// <remarks/>
        public UnityTransformType Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }

        /// <remarks/>
        public NoteTypeState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        public NoteDrawingsType Drawings
        {
            get
            {
                return this.drawingsField;
            }
            set
            {
                this.drawingsField = value;
            }
        }

        /// <remarks/>
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Only")]
        public bool AROnly
        {
            get
            {
                return this.aROnlyField;
            }
            set
            {
                this.aROnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VR-Only")]
        public bool VROnly
        {
            get
            {
                return this.vROnlyField;
            }
            set
            {
                this.vROnlyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum NoteTypeState
    {

        /// <remarks/>
        Minimized,

        /// <remarks/>
        Maximized,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class NoteDrawingsType
    {

        private NoteDrawingType[] noteDrawingsField;

        private int[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoteDrawings")]
        public NoteDrawingType[] NoteDrawings
        {
            get
            {
                return this.noteDrawingsField;
            }
            set
            {
                this.noteDrawingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID")]
        public int[] ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class NoteDrawingType
    {

        private Vector3Type[] pointsField;

        private string gUIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Points")]
        public Vector3Type[] Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }

        /// <remarks/>
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class MatlabConnectionType
    {

        private string hostField;

        private int portField;

        private bool sendField;

        private bool receiveField;

        private bool aROnlyField;

        private bool vROnlyField;

        /// <remarks/>
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }

        /// <remarks/>
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        public bool send
        {
            get
            {
                return this.sendField;
            }
            set
            {
                this.sendField = value;
            }
        }

        /// <remarks/>
        public bool receive
        {
            get
            {
                return this.receiveField;
            }
            set
            {
                this.receiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Only")]
        public bool AROnly
        {
            get
            {
                return this.aROnlyField;
            }
            set
            {
                this.aROnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VR-Only")]
        public bool VROnly
        {
            get
            {
                return this.vROnlyField;
            }
            set
            {
                this.vROnlyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class GMSECSourceType
    {

        private string connectionTypeField;

        private string serverField;

        private string subjectField;

        private int readFrequencyField;

        private bool aROnlyField;

        private bool vROnlyField;

        /// <remarks/>
        public string ConnectionType
        {
            get
            {
                return this.connectionTypeField;
            }
            set
            {
                this.connectionTypeField = value;
            }
        }

        /// <remarks/>
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        /// <remarks/>
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        public int ReadFrequency
        {
            get
            {
                return this.readFrequencyField;
            }
            set
            {
                this.readFrequencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Only")]
        public bool AROnly
        {
            get
            {
                return this.aROnlyField;
            }
            set
            {
                this.aROnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VR-Only")]
        public bool VROnly
        {
            get
            {
                return this.vROnlyField;
            }
            set
            {
                this.vROnlyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class GMSECSourcesType
    {

        private GMSECSourceType[] gMSECSourcesField;

        private int[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GMSECSources")]
        public GMSECSourceType[] GMSECSources
        {
            get
            {
                return this.gMSECSourcesField;
            }
            set
            {
                this.gMSECSourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID")]
        public int[] ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class NotesType
    {

        private NoteType[] notesField;

        private int[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notes")]
        public NoteType[] Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID")]
        public int[] ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class DualAxisRotatableObjectType
    {

        private string parentNameField;

        private UnityTransformType transformField;

        private string objectNameField;

        private string horizontalControlledObjectNameField;

        private string verticalControlledObjectNameField;

        private DualAxisRotatableObjectTypeHorizontalObjectAxis horizontalObjectAxisField;

        private DualAxisRotatableObjectTypeVerticalObjectaxis verticalObjectaxisField;

        private float minXField;

        private float maxXField;

        private float minYField;

        private float maxYField;

        private bool aROnlyField;

        private bool vROnlyField;

        /// <remarks/>
        public string ParentName
        {
            get
            {
                return this.parentNameField;
            }
            set
            {
                this.parentNameField = value;
            }
        }

        /// <remarks/>
        public UnityTransformType Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }

        /// <remarks/>
        public string ObjectName
        {
            get
            {
                return this.objectNameField;
            }
            set
            {
                this.objectNameField = value;
            }
        }

        /// <remarks/>
        public string HorizontalControlledObjectName
        {
            get
            {
                return this.horizontalControlledObjectNameField;
            }
            set
            {
                this.horizontalControlledObjectNameField = value;
            }
        }

        /// <remarks/>
        public string VerticalControlledObjectName
        {
            get
            {
                return this.verticalControlledObjectNameField;
            }
            set
            {
                this.verticalControlledObjectNameField = value;
            }
        }

        /// <remarks/>
        public DualAxisRotatableObjectTypeHorizontalObjectAxis HorizontalObjectAxis
        {
            get
            {
                return this.horizontalObjectAxisField;
            }
            set
            {
                this.horizontalObjectAxisField = value;
            }
        }

        /// <remarks/>
        public DualAxisRotatableObjectTypeVerticalObjectaxis VerticalObjectaxis
        {
            get
            {
                return this.verticalObjectaxisField;
            }
            set
            {
                this.verticalObjectaxisField = value;
            }
        }

        /// <remarks/>
        public float MinX
        {
            get
            {
                return this.minXField;
            }
            set
            {
                this.minXField = value;
            }
        }

        /// <remarks/>
        public float MaxX
        {
            get
            {
                return this.maxXField;
            }
            set
            {
                this.maxXField = value;
            }
        }

        /// <remarks/>
        public float MinY
        {
            get
            {
                return this.minYField;
            }
            set
            {
                this.minYField = value;
            }
        }

        /// <remarks/>
        public float MaxY
        {
            get
            {
                return this.maxYField;
            }
            set
            {
                this.maxYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Only")]
        public bool AROnly
        {
            get
            {
                return this.aROnlyField;
            }
            set
            {
                this.aROnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VR-Only")]
        public bool VROnly
        {
            get
            {
                return this.vROnlyField;
            }
            set
            {
                this.vROnlyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum DualAxisRotatableObjectTypeHorizontalObjectAxis
    {

        /// <remarks/>
        X,

        /// <remarks/>
        Y,

        /// <remarks/>
        Z,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum DualAxisRotatableObjectTypeVerticalObjectaxis
    {

        /// <remarks/>
        X,

        /// <remarks/>
        Y,

        /// <remarks/>
        Z,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class DrawingsType
    {

        private DrawingType[] drawingsField;

        private int[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Drawings")]
        public DrawingType[] Drawings
        {
            get
            {
                return this.drawingsField;
            }
            set
            {
                this.drawingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID")]
        public int[] ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class LocomotionSettingsType
    {

        private float teleportDistanceField;

        private float flySpeedField;

        private float touchpadSpeedField;

        private float armswingSpeedField;

        /// <remarks/>
        public float TeleportDistance
        {
            get
            {
                return this.teleportDistanceField;
            }
            set
            {
                this.teleportDistanceField = value;
            }
        }

        /// <remarks/>
        public float FlySpeed
        {
            get
            {
                return this.flySpeedField;
            }
            set
            {
                this.flySpeedField = value;
            }
        }

        /// <remarks/>
        public float TouchpadSpeed
        {
            get
            {
                return this.touchpadSpeedField;
            }
            set
            {
                this.touchpadSpeedField = value;
            }
        }

        /// <remarks/>
        public float ArmswingSpeed
        {
            get
            {
                return this.armswingSpeedField;
            }
            set
            {
                this.armswingSpeedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class VirtualEnvironmentType
    {

        private string labelField;

        private string descriptionField;

        private string assetBundleField;

        private string nameField;

        private UnityTransformType defaultUserTransformField;

        private VirtualEnvironmentTypeSkybox skyboxField;

        private VirtualEnvironmentTypeClippingPlanes clippingPlanesField;

        private LocomotionSettingsType locomotionSettingsField;

        /// <remarks/>
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string AssetBundle
        {
            get
            {
                return this.assetBundleField;
            }
            set
            {
                this.assetBundleField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public UnityTransformType DefaultUserTransform
        {
            get
            {
                return this.defaultUserTransformField;
            }
            set
            {
                this.defaultUserTransformField = value;
            }
        }

        /// <remarks/>
        public VirtualEnvironmentTypeSkybox Skybox
        {
            get
            {
                return this.skyboxField;
            }
            set
            {
                this.skyboxField = value;
            }
        }

        /// <remarks/>
        public VirtualEnvironmentTypeClippingPlanes ClippingPlanes
        {
            get
            {
                return this.clippingPlanesField;
            }
            set
            {
                this.clippingPlanesField = value;
            }
        }

        /// <remarks/>
        public LocomotionSettingsType LocomotionSettings
        {
            get
            {
                return this.locomotionSettingsField;
            }
            set
            {
                this.locomotionSettingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public partial class VirtualEnvironmentTypeSkybox
    {

        private string assetBundleField;

        private string materialNameField;

        /// <remarks/>
        public string AssetBundle
        {
            get
            {
                return this.assetBundleField;
            }
            set
            {
                this.assetBundleField = value;
            }
        }

        /// <remarks/>
        public string MaterialName
        {
            get
            {
                return this.materialNameField;
            }
            set
            {
                this.materialNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public partial class VirtualEnvironmentTypeClippingPlanes
    {

        private float nearField;

        private float farField;

        /// <remarks/>
        public float Near
        {
            get
            {
                return this.nearField;
            }
            set
            {
                this.nearField = value;
            }
        }

        /// <remarks/>
        public float Far
        {
            get
            {
                return this.farField;
            }
            set
            {
                this.farField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ViewType
    {

        private Vector3Type locationField;

        private Vector3Type rotationField;

        private float zoomField;

        private string nameField;

        /// <remarks/>
        public Vector3Type Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public Vector3Type Rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }

        /// <remarks/>
        public float Zoom
        {
            get
            {
                return this.zoomField;
            }
            set
            {
                this.zoomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        AnimationPanels,

        /// <remarks/>
        CurrentView,

        /// <remarks/>
        Description,

        /// <remarks/>
        Drawings,

        /// <remarks/>
        DualAxisRotatableObjects,

        /// <remarks/>
        Environment,

        /// <remarks/>
        GMSECSources,

        /// <remarks/>
        Marker,

        /// <remarks/>
        MatlabConnection,

        /// <remarks/>
        Notes,

        /// <remarks/>
        ObjectGenerators,

        /// <remarks/>
        Parts,

        /// <remarks/>
        PointClouds,

        /// <remarks/>
        SavedViews,

        /// <remarks/>
        VideoSources,
    }
}