//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8933
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace GSFC.ARVR.MRET.Common.Schemas
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    [System.Xml.Serialization.XmlRootAttribute("HUD", Namespace = "http://www.example.org/MRET", IsNullable = false)]
    public partial class HUDType
    {

        private DisplayType[] displayField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Display")]
        public DisplayType[] Display
        {
            get
            {
                return this.displayField;
            }
            set
            {
                this.displayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class DisplayType
    {

        private UnityTransformType transformField;

        private DisplayTypeType typeField;

        private int displayNumberField;

        private VideoSourceType feedSourceField;

        private float widthField;

        private float heightField;

        /// <remarks/>
        public UnityTransformType Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }

        /// <remarks/>
        public DisplayTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int DisplayNumber
        {
            get
            {
                return this.displayNumberField;
            }
            set
            {
                this.displayNumberField = value;
            }
        }

        /// <remarks/>
        public VideoSourceType FeedSource
        {
            get
            {
                return this.feedSourceField;
            }
            set
            {
                this.feedSourceField = value;
            }
        }

        /// <remarks/>
        public float Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public float Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class VideoSourceType
    {

        private string parentNameField;

        private string titleField;

        private VideoSourceTypeType typeField;

        private UnityTransformType transformField;

        private string sourceLinkField;

        private VideoSourceTypeSpriteType spriteTypeField;

        private string spriteDataField;

        private string imageField;

        private string valueField;

        private string standbyField;

        private string alertField;

        private long timeField;

        /// <remarks/>
        public string ParentName
        {
            get
            {
                return this.parentNameField;
            }
            set
            {
                this.parentNameField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public VideoSourceTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public UnityTransformType Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }

        /// <remarks/>
        public string SourceLink
        {
            get
            {
                return this.sourceLinkField;
            }
            set
            {
                this.sourceLinkField = value;
            }
        }

        /// <remarks/>
        public VideoSourceTypeSpriteType SpriteType
        {
            get
            {
                return this.spriteTypeField;
            }
            set
            {
                this.spriteTypeField = value;
            }
        }

        /// <remarks/>
        public string SpriteData
        {
            get
            {
                return this.spriteDataField;
            }
            set
            {
                this.spriteDataField = value;
            }
        }

        /// <remarks/>
        public string Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string Standby
        {
            get
            {
                return this.standbyField;
            }
            set
            {
                this.standbyField = value;
            }
        }

        /// <remarks/>
        public string Alert
        {
            get
            {
                return this.alertField;
            }
            set
            {
                this.alertField = value;
            }
        }

        /// <remarks/>
        public long Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum VideoSourceTypeType
    {

        /// <remarks/>
        virtualFeed,

        /// <remarks/>
        externalFeed,

        /// <remarks/>
        dataFeed,

        /// <remarks/>
        htmlFeed,

        /// <remarks/>
        spriteFeed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum VideoSourceTypeSpriteType
    {

        /// <remarks/>
        Toggle,

        /// <remarks/>
        Number,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum DisplayTypeType
    {

        /// <remarks/>
        Mini,

        /// <remarks/>
        World,

        /// <remarks/>
        HUD,
    }
}