// Copyright � 2018-2022 United States Government as represented by the Administrator
// of the National Aeronautics and Space Administration. All Rights Reserved.

namespace GOV.NASA.GSFC.XR.MRET.Schema.v0_9
{
    public partial class TransformScaleType : TransformAttributeType
    {
        /// <summary>
        /// Autogenerated code does not initialize these to 1 dues to the way scale is defined in the schema.
        /// </summary>
        public TransformScaleType() : base()
        {
            // This is a bit of a hack, but we don't want to change the defaults for size
            if (!(this is TransformSizeType))
            {
                X = ((float)(1F));
                Y = ((float)(1F));
                Z = ((float)(1F));
                referenceSpace = ReferenceSpaceType.Relative;
            }
        }
    }

}
