//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2556.0.
// 

namespace GSFC.ARVR.MRET.Common.Schemas.TimeSimulationTypes
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    [System.Xml.Serialization.XmlRootAttribute("TimeSimulation", Namespace = "http://www.example.org/MRET", IsNullable = false)]
    public partial class TimeSimulationType
    {

        private string nameField;

        private string descriptionField;

        private TimeType startTimeField;

        private float updateRateField;

        private bool pausedField;

        public TimeSimulationType()
        {
            this.updateRateField = ((float)(1F));
            this.pausedField = false;
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public TimeType StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public float UpdateRate
        {
            get
            {
                return this.updateRateField;
            }
            set
            {
                this.updateRateField = value;
            }
        }

        /// <remarks/>
        public bool Paused
        {
            get
            {
                return this.pausedField;
            }
            set
            {
                this.pausedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class TimeType
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Day", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Hour", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Millisecond", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Minute", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Month", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Second", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TimeString", typeof(TimeStringType))]
        [System.Xml.Serialization.XmlElementAttribute("TimeZone", typeof(TimeZoneType))]
        [System.Xml.Serialization.XmlElementAttribute("Year", typeof(int))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class TimeStringType
    {

        private string formatField;

        private string valueField;

        public TimeStringType()
        {
            this.formatField = "s";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("s")]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public enum TimeZoneType
    {

        /// <remarks/>
        Local,

        /// <remarks/>
        UTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        Day,

        /// <remarks/>
        Hour,

        /// <remarks/>
        Millisecond,

        /// <remarks/>
        Minute,

        /// <remarks/>
        Month,

        /// <remarks/>
        Second,

        /// <remarks/>
        TimeString,

        /// <remarks/>
        TimeZone,

        /// <remarks/>
        Year,
    }

}