//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 

namespace GSFC.ARVR.MRET.Common.Schemas
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    [System.Xml.Serialization.XmlRootAttribute("Animation", Namespace = "http://www.example.org/MRET", IsNullable = false)]
    public partial class AnimationType
    {

        private string nameField;

        private AnimationClipType[] sequenceField;

        private bool loopField;

        private bool autoplayField;

        private string versionField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sequence")]
        public AnimationClipType[] Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        public bool Loop
        {
            get
            {
                return this.loopField;
            }
            set
            {
                this.loopField = value;
            }
        }

        /// <remarks/>
        public bool Autoplay
        {
            get
            {
                return this.autoplayField;
            }
            set
            {
                this.autoplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class AnimationClipType
    {

        private ActionType actionField;

        private double startTimeField;

        private ActionType inverseField;

        /// <remarks/>
        public ActionType Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        public double StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public ActionType Inverse
        {
            get
            {
                return this.inverseField;
            }
            set
            {
                this.inverseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
    public partial class ActionType
    {

        private ActionTypeType typeField;

        private PartType partField;

        private Vector3Type positionField;

        private QuaternionType rotationField;

        private Vector3Type scaleField;

        private string partNameField;

        private DrawingType drawingField;

        private string drawingNameField;

        private NoteType noteField;

        private string noteNameField;

        private string titleField;

        private string contentField;

        private string noteDrawingNameField;

        private Vector3Type[] noteDrawingField;

        private string rigidbodyNameField;

        private bool isOnField;

        private string childObjectNameField;

        private string parentObjectNameField;

        private Vector3Type forceField;

        private ActionTypeForceMode forceModeField;

        private ActionTypeAxis axisField;

        private Vector3Type referencePointField;

        private float rotationInDegreesField;

        private float scaleToApplyField;

        private string userNameField;

        private int indexField;

        private string fileNameField;

        private ActionTypeAnnotationType annotationTypeField;

        private string uUIDField;

        /// <remarks/>
        public ActionTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public PartType Part
        {
            get
            {
                return this.partField;
            }
            set
            {
                this.partField = value;
            }
        }

        /// <remarks/>
        public Vector3Type Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        public QuaternionType Rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }

        /// <remarks/>
        public Vector3Type Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        public string PartName
        {
            get
            {
                return this.partNameField;
            }
            set
            {
                this.partNameField = value;
            }
        }

        /// <remarks/>
        public DrawingType Drawing
        {
            get
            {
                return this.drawingField;
            }
            set
            {
                this.drawingField = value;
            }
        }

        /// <remarks/>
        public string DrawingName
        {
            get
            {
                return this.drawingNameField;
            }
            set
            {
                this.drawingNameField = value;
            }
        }

        /// <remarks/>
        public NoteType Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public string NoteName
        {
            get
            {
                return this.noteNameField;
            }
            set
            {
                this.noteNameField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public string NoteDrawingName
        {
            get
            {
                return this.noteDrawingNameField;
            }
            set
            {
                this.noteDrawingNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoteDrawing")]
        public Vector3Type[] NoteDrawing
        {
            get
            {
                return this.noteDrawingField;
            }
            set
            {
                this.noteDrawingField = value;
            }
        }

        /// <remarks/>
        public string RigidbodyName
        {
            get
            {
                return this.rigidbodyNameField;
            }
            set
            {
                this.rigidbodyNameField = value;
            }
        }

        /// <remarks/>
        public bool IsOn
        {
            get
            {
                return this.isOnField;
            }
            set
            {
                this.isOnField = value;
            }
        }

        /// <remarks/>
        public string ChildObjectName
        {
            get
            {
                return this.childObjectNameField;
            }
            set
            {
                this.childObjectNameField = value;
            }
        }

        /// <remarks/>
        public string ParentObjectName
        {
            get
            {
                return this.parentObjectNameField;
            }
            set
            {
                this.parentObjectNameField = value;
            }
        }

        /// <remarks/>
        public Vector3Type Force
        {
            get
            {
                return this.forceField;
            }
            set
            {
                this.forceField = value;
            }
        }

        /// <remarks/>
        public ActionTypeForceMode ForceMode
        {
            get
            {
                return this.forceModeField;
            }
            set
            {
                this.forceModeField = value;
            }
        }

        /// <remarks/>
        public ActionTypeAxis Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }

        /// <remarks/>
        public Vector3Type ReferencePoint
        {
            get
            {
                return this.referencePointField;
            }
            set
            {
                this.referencePointField = value;
            }
        }

        /// <remarks/>
        public float RotationInDegrees
        {
            get
            {
                return this.rotationInDegreesField;
            }
            set
            {
                this.rotationInDegreesField = value;
            }
        }

        /// <remarks/>
        public float ScaleToApply
        {
            get
            {
                return this.scaleToApplyField;
            }
            set
            {
                this.scaleToApplyField = value;
            }
        }

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        public ActionTypeAnnotationType AnnotationType
        {
            get
            {
                return this.annotationTypeField;
            }
            set
            {
                this.annotationTypeField = value;
            }
        }

        /// <remarks/>
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum ActionTypeType
    {

        /// <remarks/>
        MoveObject,

        /// <remarks/>
        AddObject,

        /// <remarks/>
        DeleteObject,

        /// <remarks/>
        AddDrawing,

        /// <remarks/>
        DeleteDrawing,

        /// <remarks/>
        AddNote,

        /// <remarks/>
        DeleteNote,

        /// <remarks/>
        MoveNote,

        /// <remarks/>
        ChangeNoteText,

        /// <remarks/>
        ChangeNoteState,

        /// <remarks/>
        AddNoteDrawing,

        /// <remarks/>
        DeleteNoteDrawing,

        /// <remarks/>
        SetFinalIKPos,

        /// <remarks/>
        SetMatlabIKPos,

        /// <remarks/>
        AddPointToLine,

        /// <remarks/>
        DeletePointFromLine,

        /// <remarks/>
        SwitchPhysicsState,

        /// <remarks/>
        SwitchGravityState,

        /// <remarks/>
        ChangeParent,

        /// <remarks/>
        ApplyForce,

        /// <remarks/>
        RotateEnvironment,

        /// <remarks/>
        ScaleEnvironment,

        /// <remarks/>
        MoveUser,

        /// <remarks/>
        Unset,

        /// <remarks/>
        AnnotationGoTo,

        /// <remarks/>
        EndAnnotation,

        /// <remarks/>
        PauseAnnotation,

        /// <remarks/>
        PlayAnnotation,

        /// <remarks/>
        StartAnnotation,

        /// <remarks/>
        StopAnnotation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum ActionTypeForceMode
    {

        /// <remarks/>
        Acceleration,

        /// <remarks/>
        Force,

        /// <remarks/>
        Impulse,

        /// <remarks/>
        VelocityChange,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum ActionTypeAxis
    {

        /// <remarks/>
        X,

        /// <remarks/>
        Y,

        /// <remarks/>
        Z,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.example.org/MRET")]
    public enum ActionTypeAnnotationType
    {

        /// <remarks/>
        Text,

        /// <remarks/>
        Audio,

        /// <remarks/>
        Unset,
    }
}