//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/MRET", IsNullable = false)]
public partial class TextAnnotation
{

    private TextListType textsField;

    private float timePerTextField;

    private bool loopField;

    private string attachToField;

    private string versionField;

    /// <remarks/>
    public TextListType Texts
    {
        get
        {
            return this.textsField;
        }
        set
        {
            this.textsField = value;
        }
    }

    /// <remarks/>
    public float TimePerText
    {
        get
        {
            return this.timePerTextField;
        }
        set
        {
            this.timePerTextField = value;
        }
    }

    /// <remarks/>
    public bool Loop
    {
        get
        {
            return this.loopField;
        }
        set
        {
            this.loopField = value;
        }
    }

    /// <remarks/>
    public string AttachTo
    {
        get
        {
            return this.attachToField;
        }
        set
        {
            this.attachToField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/MRET")]
public partial class TextListType
{

    private string[] textsField;

    private int[] idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Texts")]
    public string[] Texts
    {
        get
        {
            return this.textsField;
        }
        set
        {
            this.textsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ID")]
    public int[] ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}
